### ISSUE TITLE
Update the minecraft api library

### ISSUE THREAD

**Issue by raypitmon** [CoderDojoTC/python-minecraft#5]
Hi,

It looks like some useful functions have been added to the API, such as player.getRotation() that are not included in this version.

See here: http://www.stuffaboutcode.com/p/minecraft-api-reference.html

It would be nice to update.

thanks!

-Ray

**Comment by mikemccllstr** [comment]
Hi Ray,

I totally agree. I think we will need to take an updated version of the RasbperryJuice plugin along with the new MCPI code. I'm working on change to let us more easily build and distribute the images that contain the plugins. Once that's in place, this can follow quickly.


Mike
