### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by jfromaniello** [CoderDojoTC/python-minecraft#8]
I followed all instructions but I get a "Failed to connect to server" when I try to join what it looks like a perfectly online server. Here is a GIF showing how it looks:

![minecraft-issue](https://cloud.githubusercontent.com/assets/178512/7550403/aae9a30e-f637-11e4-904b-16907776cf1d.gif)

**Comment by jfromaniello** [comment]
Question: is there a way to see the logs of the server?

**Comment by mikemccllstr** [comment]
Hi José,

Hi, can you tell me a little more about your setup? Which instructions are you following to set up and launch the server? Are you using a Mac? Are you able to connect to IPython?

The instructions on this page are the most reliable: http://python-minecraft.readthedocs.org/en/latest/other-setups/vagrant.html.


Mike

**Comment by jfromaniello** [comment]
Hi Mike,  I think it was a problem with the client side,  I reinstalled minecraft  and everything seems to be working fine now. 

Thank you very much for this awesome project, cheers from Córdoba, Argentina.
